* 2022-05-23
** Tasks [2/2]
*** DONE Read GSoC email materials
1. Accepted Contributor Information page
2. GSoC roles and responsibilities page
*** DONE Setup mirror repo on GitHub for project management
https://github.com/zarak/goal

I had to clear large files before I could push to the repo - i.e. history is rewritten
#+begin_src bash
bfg --strip-blobs-bigger-than 50M
git reflog expire --expire=now --all
git gc --prune=now --aggressive
#+end_src

bfg summary
#+begin_src
Cleaning
--------

Found 408 commits
Cleaning commits:       100% (408/408)
Cleaning commits completed in 238 ms.

Updating 2 Refs
---------------

	Ref                          Before     After
	------------------------------------------------
	refs/heads/main            | 64c86696 | 501f85a7
	refs/remotes/origin/master | 64c86696 | 501f85a7

Updating references:    100% (2/2)
...Ref update completed in 18 ms.

Commit Tree-Dirt History
------------------------

	Earliest                                              Latest
	|                                                          |
	................DDmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmm

	D = dirty commits (file tree fixed)
	m = modified commits (commit message or parents changed)
	. = clean commits (no changes to file tree)

	                        Before     After
	-------------------------------------------
	First modified commit | bd7e9615 | 29bde34b
	Last dirty commit     | 64ca2c48 | eccd1685

Deleted files
-------------

	Filename     Git id
	---------------------------------------------------------
	spikes.csv | 864d329c (68.7 MB), ff1d953a (106.9 MB), ...
#+end_src
** Notes
*** Clearing large files from git cache
The git cache seems to have large files - should these be pruned?

Find the 10 largest blobs.
#+begin_src bash
git verify-pack -v .git/objects/pack/pack-7741dec2030092fba0aed6b804e03a9c8094c1c9.idx \
                                              | sort -k 3 -n \
                                              | tail -10
#+end_src

The large files are data files in the applications dir.
#+begin_src bash
git rev-list --objects --all | grep b50e4b6
#+end_src

* 2022-05-24
** Tasks [2/3]
*** DONE Write derivations for each =Goal= module
1. core
2. probability
3. graphical
4. geometry
*** DONE Combine derivations into top-level nix shell
** Notes
Use =cabal2nix= in each of the modules to generate derivations and then combine them in a shell.nix file. I should also create a flake.nix, but for now I think this is all I need to import in the hasktorch-skeleton shell.
* 2022-05-25
** Tasks [0/1]
*** TODO Set up Payoneer registration
